// src/js/data.js

// Dados das obras
const obrasData = [
    { "titulo": "Família de Pescadores", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/familia-pescadores.png" },
    { "titulo": "A Ceia Larga", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/a-ceia-larga.png" },
    { "titulo": "Plantio de Girassol", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/plantio-girassol.png" },
    { "titulo": "O Carro de Boi", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/o-carro-de-boi.png" },
    { "titulo": "Os Pássaros", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/os-passaros.png" },
    { "titulo": "Reunião dos Bichos", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/reuniao-dos-bichos.png" },
    { "titulo": "Mulheres e Cactos", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/mulheres-e-cactos.png" },
    { "titulo": "A Sereia e os Pássaros", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/a-sereia-e-os-passaros.png" },
    { "titulo": "O Palhaço na Rua", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/o-palhaco-na-rua.png" },
    { "titulo": "Pastor de Ovelhas", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/pastor-de-ovelhas.png" },
    { "titulo": "São Francisco", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "56x41", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/sao-francisco.png" },
    { "titulo": "Mazurca no Cajueiro", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "70x50", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/mazurca-no-cajueiro.png" },
    { "titulo": "O Presépio", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "70x50", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/o-presepio.png" },
    { "titulo": "Pau de Sebo", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "70x50", "valor": "R$ 1.180,00", "imagem": "./src/assets/images/pau-de-sebo.png" },
    { "titulo": "Belchior", "artista": "Baccaro Borges", "tecnica": "Xilogravura", "tamanho": "60x40", "valor": "R$ 780,00", "imagem": "./src/assets/images/belchior.png" },
    { "titulo": "Lua Cheia", "artista": "J. Borges", "tecnica": "Xilogravura", "tamanho": "70x50", "valor": "R$ 1.300,00", "imagem": "./src/assets/images/lua-cheia.png" },
    { "titulo": "Peixe no Mar", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "82x64", "valor": "R$ 3.200,00", "imagem": "https://placehold.co/600x800/EC4899/FFFFFF?text=Peixe+Mar" },
    { "titulo": "Rendeira Azul, Preto e Laranja", "artista": "Aldemir Martins", "tecnica": "Litogravura", "tamanho": "84x66", "valor": "R$ 3.400,00", "imagem": "https://placehold.co/600x800/10B981/FFFFFF?text=Rendeira" },
    { "titulo": "Gato Garfield", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "89x68", "valor": "R$ 3.700,00", "imagem": "https://placehold.co/600x800/6B7280/FFFFFF?text=Gato+Garfield" },
    { "titulo": "Gato Azul", "artista": "Aldemir Martins", "tecnica": "Litogravura", "tamanho": "88x68", "valor": "R$ 2.900,00", "imagem": "https://placehold.co/600x800/FACC15/FFFFFF?text=Gato+Azul" },
    { "titulo": "Gato Cinza Quadrado", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "68x62", "valor": "R$ 1.200,00", "imagem": "https://placehold.co/600x800/FB923C/FFFFFF?text=Gato+Cinza" },
    { "titulo": "Coruja Amarela", "artista": "Aldemir Martins", "tecnica": "Litografia", "tamanho": "50x40", "valor": "R$ 1.000,00", "imagem": "https://placehold.co/600x800/E879F9/FFFFFF?text=Coruja+Amarela" },
    { "titulo": "Obra sem título", "artista": "Aldemir Martins", "tecnica": "Litogravura", "tamanho": "48x40", "valor": "R$ 1.500,00", "imagem": "https://placehold.co/600x800/3B82F6/FFFFFF?text=Obra+Aldemir" },
    { "titulo": "Jarro Flores G", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "88x68", "valor": "R$ 2.800,00", "imagem": "https://placehold.co/600x800/EF4444/FFFFFF?text=Jarro+Flores+G" },
    { "titulo": "Jarro Flores P", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "44x68", "valor": "R$ 1.000,00", "imagem": "https://placehold.co/600x800/14B8A6/FFFFFF?text=Jarro+Flores+P" },
    { "titulo": "Marinha G", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "110x88", "valor": "R$ 3.200,00", "imagem": "https://placehold.co/600x800/A855F7/FFFFFF?text=Marinha+G" },
    { "titulo": "Marinha", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "90x70", "valor": "R$ 2.800,00", "imagem": "https://placehold.co/600x800/F472B6/FFFFFF?text=Marinha" },
    { "titulo": "Coruja Vermelha", "artista": "Aldemir Martins", "tecnica": "Xilogravura", "tamanho": "50x40", "valor": "R$ 1.000,00", "imagem": "https://placehold.co/600x800/6366F1/FFFFFF?text=Coruja+Vermelha" },
    { "titulo": "Galo Verde e Amarelo", "artista": "Aldemir Martins", "tecnica": "Litografia", "tamanho": "92x71", "valor": "R$ 3.300,00", "imagem": "https://placehold.co/600x800/06B6D4/FFFFFF?text=Galo+Verde+Amarelo" },
    { "titulo": "Cangaceiro (1988)", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "63x50", "valor": "R$ 2.500,00", "imagem": "https://placehold.co/600x800/D946EF/FFFFFF?text=Cangaceiro" },
    { "titulo": "Gato Vermelho Sentado", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "68x88", "valor": "R$ 1.600,00", "imagem": "https://placehold.co/600x800/8B5CF6/FFFFFF?text=Gato+Vermelho" },
    { "titulo": "Gato Malhado M", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "88x68", "valor": "R$ 1.700,00", "imagem": "https://placehold.co/600x800/EC4899/FFFFFF?text=Gato+Malhado" },
    { "titulo": "Família de Gatos", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "96x52", "valor": "R$ 1.700,00", "imagem": "https://placehold.co/600x800/10B981/FFFFFF?text=Familia+Gatos" },
    { "titulo": "Gato Rajado Deitado P", "artista": "Aldemir Martins", "tecnica": "Serigrafia", "tamanho": "68x52", "valor": "R$ 1.200,00", "imagem": "https://placehold.co/600x800/6B7280/FFFFFF?text=Gato+Rajado" },
    { "titulo": "Fusca P", "artista": "Kleber Ventura", "tecnica": "Gravura", "tamanho": "30x40", "valor": "R$ 350,00", "imagem": "https://placehold.co/600x800/FACC15/FFFFFF?text=Fusca" },
    { "titulo": "Kombi Azul", "artista": "Kleber Ventura", "tecnica": "Gravura", "tamanho": "30x40", "valor": "R$ 350,00", "imagem": "https://placehold.co/600x800/FB923C/FFFFFF?text=Kombi+Azul" },
    { "titulo": "Anjo", "artista": "Paulo Francisco", "tecnica": "Técnica Mista", "tamanho": "46x96", "valor": "R$ 800,00", "imagem": "https://placehold.co/600x800/E879F9/FFFFFF?text=Anjo" },
    { "titulo": "Madona", "artista": "Paulo Francisco", "tecnica": "Técnica Mista", "tamanho": "57x90", "valor": "R$ 950,00", "imagem": "https://placehold.co/600x800/3B82F6/FFFFFF?text=Madona" },
    { "titulo": "Madona Lilás", "artista": "Paulo Francisco", "tecnica": "Técnica Mista", "tamanho": "56x90", "valor": "R$ 950,00", "imagem": "https://placehold.co/600x800/EF4444/FFFFFF?text=Madona+Lilas" },
    { "titulo": "Obra sem título", "artista": "Camélio Cruz", "tecnica": "Pintura", "tamanho": "60x60", "valor": "R$ 700,00", "imagem": "https://placehold.co/600x800/14B8A6/FFFFFF?text=Obra+Camelio" },
    { "titulo": "Obra sem título", "artista": "Francisco Lisboa", "tecnica": "Escultura", "tamanho": "78x73", "valor": "R$ 1.800,00", "imagem": "https://placehold.co/600x800/A855F7/FFFFFF?text=Obra+Lisboa" },
    { "titulo": "São Francisco", "artista": "Chico Rabelo", "tecnica": "Madeira", "tamanho": "40x80", "valor": "R$ 1.200,00", "imagem": "https://placehold.co/600x800/F472B6/FFFFFF?text=Sao+Francisco+Rabelo" },
    { "titulo": "Obra sem título", "artista": "Edmar Gonçalves", "tecnica": "Cerâmica", "tamanho": "30x30", "valor": "R$ 500,00", "imagem": "https://placehold.co/600x800/6366F1/FFFFFF?text=Obra+Edmar" },
    { "titulo": "Obra sem título", "artista": "Ramon Carceres", "tecnica": "Acrílica sobre tela", "tamanho": "73x73", "valor": "R$ 2.100,00", "imagem": "https://placehold.co/600x800/06B6D4/FFFFFF?text=Obra+Carceres" },
    { "titulo": "Pombo Azul", "artista": "Zé Wilson", "tecnica": "Pintura", "tamanho": "135x86", "valor": "R$ 2.500,00", "imagem": "https://placehold.co/600x800/D946EF/FFFFFF?text=Pombo+Azul" },
    { "titulo": "Obra sem título", "artista": "Toyota", "tecnica": "Instalação", "tamanho": "200x150", "valor": "R$ 3.000,00", "imagem": "https://placehold.co/600x800/8B5CF6/FFFFFF?text=Obra+Toyota" },
    { "titulo": "Obra sem título", "artista": "Chico da Silva por Claudionor", "tecnica": "Reprodução", "tamanho": "70x50", "valor": "R$ 900,00", "imagem": "https://placehold.co/600x800/EC4899/FFFFFF?text=Obra+Chico+Claudionor" },
    { "titulo": "Lambreta", "artista": "Kleber Ventura", "tecnica": "Gravura", "tamanho": "30x40", "valor": "R$ 350,00", "imagem": "https://placehold.co/600x800/10B981/FFFFFF?text=Lambreta" },
    { "titulo": "Pavão Misteriosa", "artista": "José Lourenço", "tecnica": "Xilogravura", "tamanho": "50x70", "valor": "R$ 1.250,00", "imagem": "https://placehold.co/600x800/6B7280/FFFFFF?text=Pavao+Misteriosa" },
    { "titulo": "Dom Quixote", "artista": "Jeferson Campos", "tecnica": "Pintura", "tamanho": "80x100", "valor": "R$ 2.800,00", "imagem": "https://placehold.co/600x800/FACC15/FFFFFF?text=Dom+Quixote" },
    { "titulo": "São Jorge", "artista": "José Lourenço", "tecnica": "Xilogravura", "tamanho": "60x80", "valor": "R$ 1.300,00", "imagem": "https://placehold.co/600x800/FB923C/FFFFFF?text=Sao+Jorge" },
    { "titulo": "Amarelo", "artista": "Fukuda", "tecnica": "Abstrato", "tamanho": "70x70", "valor": "R$ 1.500,00", "imagem": "https://placehold.co/600x800/E879F9/FFFFFF?text=Amarelo" },
    { "titulo": "Azul", "artista": "Fukuda", "tecnica": "Abstrato", "tamanho": "70x70", "valor": "R$ 1.500,00", "imagem": "https://placehold.co/600x800/3B82F6/FFFFFF?text=Azul" },
    { "titulo": "Obra sem título", "artista": "Babinski", "tecnica": "Escultura", "tamanho": "50x50", "valor": "R$ 900,00", "imagem": "https://placehold.co/600x800/EF4444/FFFFFF?text=Obra+Babinski" },
    { "titulo": "Obra sem título", "artista": "Silvio Rabelo", "tecnica": "Pintura", "tamanho": "60x80", "valor": "R$ 1.100,00", "imagem": "https://placehold.co/600x800/14B8A6/FFFFFF?text=Obra+Silvio" },
    { "titulo": "Obra sem título", "artista": "Rubem Lindolf", "tecnica": "Desenho", "tamanho": "40x50", "valor": "R$ 600,00", "imagem": "https://placehold.co/600x800/A855F7/FFFFFF?text=Obra+Lindolf" },
    { "titulo": "Casário", "artista": "Chico Rabelo", "tecnica": "Pintura", "tamanho": "70x90", "valor": "R$ 1.800,00", "imagem": "https://placehold.co/600x800/F472B6/FFFFFF?text=Casario" },
    { "titulo": "Obra sem título", "artista": "Gilberto Brito", "tecnica": "Fotografia", "tamanho": "60x90", "valor": "R$ 750,00", "imagem": "https://placehold.co/600x800/6366F1/FFFFFF?text=Obra+Gilberto" },
    { "titulo": "Shelliane no Espelho", "artista": "Expedito Lima", "tecnica": "Pintura", "tamanho": "80x80", "valor": "R$ 2.000,00", "imagem": "https://placehold.co/600x800/06B6D4/FFFFFF?text=Shelliane" }
];

// Biografias dos artistas (para o modal)
const artistBios = {
    "J. Borges": "J. Borges é um dos maiores nomes da xilogravura brasileira. Nascido em Pernambuco, suas obras retratam o cotidiano nordestino com humor, crítica e lirismo, sendo reconhecido internacionalmente pela sua arte vibrante e autêntica.",
    "Aldemir Martins": "Aldemir Martins foi um pintor, gravador, ilustrador e desenhista brasileiro. Conhecido por suas representações de gatos, cangaceiros e paisagens nordestinas, sua obra é marcada por cores vibrantes e um estilo único que celebra a cultura brasileira.",
    "Kleber Ventura": "Kleber Ventura é um gravurista contemporâneo que se destaca por suas obras que capturam a essência do cotidiano e elementos nostálgicos da cultura brasileira com um toque moderno.",
    "Paulo Francisco": "Paulo Francisco é um artista que explora a técnica mista para criar obras com forte apelo espiritual e figurativo, muitas vezes abordando temas religiosos e simbólicos com sensibilidade.",
    "Camélio Cruz": "Camélio Cruz é um artista que se expressa através da pintura, com um estilo que reflete a vivacidade e as cores do Brasil, explorando temas do cotidiano e da natureza.",
    "Francisco Lisboa": "Francisco Lisboa é um escultor que trabalha com materiais diversos, criando peças que dialogam com a tradição e a modernidade, muitas vezes com um foco na figura humana.",
    "Chico Rabelo": "Chico Rabelo é conhecido por suas obras em madeira e pinturas que retratam a cultura popular e as paisagens brasileiras com um olhar único e autêntico.",
    "Edmar Gonçalves": "Edmar Gonçalves é um ceramista que transforma o barro em arte, criando peças que combinam funcionalidade e beleza, inspiradas na riqueza da cultura popular.",
    "Ramon Carceres": "Ramon Carceres é um pintor que utiliza a acrílica sobre tela para criar obras vibrantes e expressivas, com um estilo que transita entre o figurativo e o abstrato.",
    "Zé Wilson": "Zé Wilson é um pintor que se destaca por suas representações de animais e cenas do cotidiano, com um estilo que evoca a simplicidade e a beleza da vida no campo.",
    "Toyota": "Toyota é um artista que desafia as convenções através de instalações e obras conceituais, explorando novas formas de expressão e interação com o público.",
    "Claudionor": "Claudionor é um artista que, através de suas reproduções, presta homenagem a grandes mestres da arte brasileira, como Chico da Silva, mantendo viva a memória e o legado desses artistas.",
    "José Lourenço": "José Lourenço é um xilogravurista que, com suas obras, narra histórias e lendas do folclore brasileiro, transportando o espectador para um universo de mistério e tradição.",
    "Jeferson Campos": "Jeferson Campos é um pintor que se inspira em temas clássicos e literários, como Dom Quixote, para criar obras com uma narrativa visual rica e envolvente.",
    "Fukuda": "Fukuda é um artista abstrato que explora a cor e a forma para criar composições dinâmicas e expressivas, convidando o espectador a uma experiência sensorial única.",
    "Babinski": "Babinski é um escultor que trabalha com formas orgânicas e abstratas, criando peças que exploram a relação entre o espaço e o volume.",
    "Silvio Rabelo": "Silvio Rabelo é um pintor que se dedica a retratar paisagens e cenas urbanas, com um estilo que capta a atmosfera e a luz dos ambientes.",
    "Rubem Lindolf": "Rubem Lindolf é um desenhista que se destaca pela delicadeza e precisão de seus traços, criando obras que exploram a figura humana e a natureza com sensibilidade.",
    "Gilberto Brito": "Gilberto Brito é um fotógrafo que captura a essência do Brasil através de suas lentes, revelando a beleza e a diversidade da cultura e da paisagem.",
    "Expedito Lima": "Expedito Lima é um pintor que se expressa através de obras figurativas, muitas vezes com um toque de realismo mágico, explorando temas do cotidiano e da imaginação."
};
